name: riverpod_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.5.2
  infinite_scroll_pagination: ^4.1.0
  json_annotation: ^4.9.0
  number_paginator: ^0.4.3
  path_url_strategy_module: ^1.0.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
