name: riverpod_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  infinite_scroll_pagination: ^4.1.0
  json_annotation: ^4.9.0
  number_paginator: ^0.4.3
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
