// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGztkarZjcmt--BXxDAotvxoZ1uGYtPo',
    appId: '1:929918325224:web:82ad7221a7e81a8462145d',
    messagingSenderId: '929918325224',
    projectId: 'study-project-on-riverpod',
    authDomain: 'study-project-on-riverpod.firebaseapp.com',
    storageBucket: 'study-project-on-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4Tgg1_5JyNdlnwAgDp6Ehpexp6Khp6I',
    appId: '1:929918325224:android:6842cfe55b3dc53e62145d',
    messagingSenderId: '929918325224',
    projectId: 'study-project-on-riverpod',
    storageBucket: 'study-project-on-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnkwrByr5jEIBUSbsw4jMwq0bDx_Bfj5k',
    appId: '1:929918325224:ios:f0a3df90f9c618d762145d',
    messagingSenderId: '929918325224',
    projectId: 'study-project-on-riverpod',
    storageBucket: 'study-project-on-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnkwrByr5jEIBUSbsw4jMwq0bDx_Bfj5k',
    appId: '1:929918325224:ios:f0a3df90f9c618d762145d',
    messagingSenderId: '929918325224',
    projectId: 'study-project-on-riverpod',
    storageBucket: 'study-project-on-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );
}

/*
Platform  Firebase App Id
web       1:929918325224:web:82ad7221a7e81a8462145d
android   1:929918325224:android:6842cfe55b3dc53e62145d
ios       1:929918325224:ios:f0a3df90f9c618d762145d
macos     1:929918325224:ios:f0a3df90f9c618d762145d


 */
