// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVrt-413aacV887vuidGwq99qr42nYBU',
    appId: '1:499261259777:web:6d5fd0891192a04f94c000',
    messagingSenderId: '499261259777',
    projectId: 'rivepod-study-project',
    authDomain: 'rivepod-study-project.firebaseapp.com',
    storageBucket: 'rivepod-study-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4QywMvwhuP_eu79xhVPzgxunw7g45v0',
    appId: '1:499261259777:android:b69820081a35461894c000',
    messagingSenderId: '499261259777',
    projectId: 'rivepod-study-project',
    storageBucket: 'rivepod-study-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjoK16ds_av2lvOwk9ZE9IV_bKg1Dcb8',
    appId: '1:499261259777:ios:3f72d1a0763e1fea94c000',
    messagingSenderId: '499261259777',
    projectId: 'rivepod-study-project',
    storageBucket: 'rivepod-study-project.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjoK16ds_av2lvOwk9ZE9IV_bKg1Dcb8',
    appId: '1:499261259777:ios:3f72d1a0763e1fea94c000',
    messagingSenderId: '499261259777',
    projectId: 'rivepod-study-project',
    storageBucket: 'rivepod-study-project.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );
}
